//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.29 at 08:01:10 AM COT 
//


package uniandes.migration.microservices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="from">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="qualifiedType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="sourceMicroservice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="fromMethod" type="{}signature"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="to">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="qualifiedType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="targetMicroservice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="toMethod" type="{}signature"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "from",
    "to"
})
@XmlRootElement(name = "methodInvocation")
public class MethodInvocation {

    @XmlElement(required = true)
    protected MethodInvocation.From from;
    @XmlElement(required = true)
    protected MethodInvocation.To to;

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link MethodInvocation.From }
     *     
     */
    public MethodInvocation.From getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link MethodInvocation.From }
     *     
     */
    public void setFrom(MethodInvocation.From value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link MethodInvocation.To }
     *     
     */
    public MethodInvocation.To getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link MethodInvocation.To }
     *     
     */
    public void setTo(MethodInvocation.To value) {
        this.to = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="qualifiedType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="sourceMicroservice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="fromMethod" type="{}signature"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "qualifiedType",
        "sourceMicroservice",
        "fromMethod"
    })
    public static class From {

        @XmlElement(required = true)
        protected String qualifiedType;
        protected String sourceMicroservice;
        @XmlElement(required = true)
        protected Signature fromMethod;

        /**
         * Gets the value of the qualifiedType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQualifiedType() {
            return qualifiedType;
        }

        /**
         * Sets the value of the qualifiedType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQualifiedType(String value) {
            this.qualifiedType = value;
        }

        /**
         * Gets the value of the sourceMicroservice property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSourceMicroservice() {
            return sourceMicroservice;
        }

        /**
         * Sets the value of the sourceMicroservice property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSourceMicroservice(String value) {
            this.sourceMicroservice = value;
        }

        /**
         * Gets the value of the fromMethod property.
         * 
         * @return
         *     possible object is
         *     {@link Signature }
         *     
         */
        public Signature getFromMethod() {
            return fromMethod;
        }

        /**
         * Sets the value of the fromMethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link Signature }
         *     
         */
        public void setFromMethod(Signature value) {
            this.fromMethod = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="qualifiedType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="targetMicroservice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="toMethod" type="{}signature"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "qualifiedType",
        "targetMicroservice",
        "toMethod"
    })
    public static class To {

        @XmlElement(required = true)
        protected String qualifiedType;
        protected String targetMicroservice;
        @XmlElement(required = true)
        protected Signature toMethod;

        /**
         * Gets the value of the qualifiedType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQualifiedType() {
            return qualifiedType;
        }

        /**
         * Sets the value of the qualifiedType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQualifiedType(String value) {
            this.qualifiedType = value;
        }

        /**
         * Gets the value of the targetMicroservice property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTargetMicroservice() {
            return targetMicroservice;
        }

        /**
         * Sets the value of the targetMicroservice property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTargetMicroservice(String value) {
            this.targetMicroservice = value;
        }

        /**
         * Gets the value of the toMethod property.
         * 
         * @return
         *     possible object is
         *     {@link Signature }
         *     
         */
        public Signature getToMethod() {
            return toMethod;
        }

        /**
         * Sets the value of the toMethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link Signature }
         *     
         */
        public void setToMethod(Signature value) {
            this.toMethod = value;
        }

    }

}
