//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.29 at 08:01:10 AM COT 
//


package uniandes.migration.microservices;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;choice>
 *           &lt;element ref="{}attribute"/>
 *           &lt;element ref="{}methodInvocation"/>
 *           &lt;element ref="{}methodParameter"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attributeOrMethodInvocationOrMethodParameter"
})
@XmlRootElement(name = "relationships")
public class Relationships {

    @XmlElements({
        @XmlElement(name = "attribute", type = Attribute.class),
        @XmlElement(name = "methodInvocation", type = MethodInvocation.class),
        @XmlElement(name = "methodParameter", type = MethodParameter.class)
    })
    protected List<Object> attributeOrMethodInvocationOrMethodParameter;

    /**
     * Gets the value of the attributeOrMethodInvocationOrMethodParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributeOrMethodInvocationOrMethodParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributeOrMethodInvocationOrMethodParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Attribute }
     * {@link MethodInvocation }
     * {@link MethodParameter }
     * 
     * 
     */
    public List<Object> getAttributeOrMethodInvocationOrMethodParameter() {
        if (attributeOrMethodInvocationOrMethodParameter == null) {
            attributeOrMethodInvocationOrMethodParameter = new ArrayList<Object>();
        }
        return this.attributeOrMethodInvocationOrMethodParameter;
    }

}
